config/routes.rb
Rails.application.routes.draw do

  get 'restricted' => 'home#restricted'

  get 'login' => 'logins#login'
  get 'logout' => 'logins#logout'
  get 'signup' => 'signups#create'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def require_user
    unless current_user
      session[:last_url] = request.get? ? url_for(params.dup.permit!.except(:domain, :host, :port, :protocol, :subdomain)) : url_for
      redirect_to new_login_url
    end
  end

  def current_user
    @_current_user ||= AuthRocket::Session.from_token(session[:ar_token]).try(:user)
  end
  helper_method :current_user

  def new_login_url
    ENV['AUTHROCKET_LOGIN_URL']
  end
  helper_method :new_login_url

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :require_user, only: :restricted

  def index
  end

  def restricted
  end

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController

  def login
    if params[:token]
      if AuthRocket::Session.from_token(params[:token])
        session[:ar_token] = params[:token]
      end
    end
    unless require_user
      redirect_to session[:last_url] || root_path
      session[:last_url] = nil
    end
  end

  def logout
    # assumes realm is using managed sessions (remove if that's not the case):
    AuthRocket::Session.delete session[:ar_token] if session[:ar_token]

    session[:ar_token] = nil
    redirect_to root_path, notice: 'You have been logged out.'
  end

end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController

  def create
    if params[:token]
      user = AuthRocket::User.create(token: params[:token])
      if user.valid?
        flash[:notice] = 'Thanks for signing up!'
        # requires realm to use managed sessions (remove if that's not the case):
        session[:ar_token] = user.create_session(ip: request.ip, client: request.headers['User-Agent']).try(:token)
      else
        flash[:alert] = user.errors.full_messages.join(' ')
      end
      redirect_to root_path
    else
      redirect_to new_signup_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def new_signup_url
    new_login_url+'signup'
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/home/index.html.erb
<h1>Home</h1>

<p>This is a public page.</p>

app/views/home/restricted.html.erb
<h1>Restricted</h1>

<p>This page requires a login.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LrRailsHosted</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
    <p>Welcome, <%= current_user.name %>! (<%= link_to 'Logout', logout_path %>)</p>
  <% else %>
    <p>
      <%= link_to 'Signup', new_signup_url %> |
      <%= link_to 'Login', new_login_url %>
    </p>
  <% end %>

  <%= safe_join [:alert, :notice].map{|f| content_tag(:p, flash[f]) if flash[f] }.compact %>

  <p>
    <%= link_to 'Home', root_path %> |
    <%= link_to 'Restricted', restricted_path %>
  </p>

<%= yield %>

</body>
</html>